if(EXISTS "/workspace/helm-project/libs/dagr/build-ci/tests/prop_invalid_enum[1]_tests.cmake")
  include("/workspace/helm-project/libs/dagr/build-ci/tests/prop_invalid_enum[1]_tests.cmake")
else()
  add_test(prop_invalid_enum_NOT_BUILT prop_invalid_enum_NOT_BUILT)
endif()
