if(EXISTS "/workspace/helm-project/libs/dagr/build-ci/tests/prop_idempotent_shutdown[1]_tests.cmake")
  include("/workspace/helm-project/libs/dagr/build-ci/tests/prop_idempotent_shutdown[1]_tests.cmake")
else()
  add_test(prop_idempotent_shutdown_NOT_BUILT prop_idempotent_shutdown_NOT_BUILT)
endif()
