if(EXISTS "/workspace/helm-project/libs/dagr/build-ci/tests/prop_duplicate_stream[1]_tests.cmake")
  include("/workspace/helm-project/libs/dagr/build-ci/tests/prop_duplicate_stream[1]_tests.cmake")
else()
  add_test(prop_duplicate_stream_NOT_BUILT prop_duplicate_stream_NOT_BUILT)
endif()
