if(EXISTS "/workspace/helm-project/libs/dagr/build-ci/tests/prop_yaml_roundtrip[1]_tests.cmake")
  include("/workspace/helm-project/libs/dagr/build-ci/tests/prop_yaml_roundtrip[1]_tests.cmake")
else()
  add_test(prop_yaml_roundtrip_NOT_BUILT prop_yaml_roundtrip_NOT_BUILT)
endif()
