if(EXISTS "/workspace/helm-project/libs/dagr/build-ci/tests/prop_no_orphan[1]_tests.cmake")
  include("/workspace/helm-project/libs/dagr/build-ci/tests/prop_no_orphan[1]_tests.cmake")
else()
  add_test(prop_no_orphan_NOT_BUILT prop_no_orphan_NOT_BUILT)
endif()
