if(EXISTS "/workspace/helm-project/libs/dagr/build-ci/tests/prop_topological_order[1]_tests.cmake")
  include("/workspace/helm-project/libs/dagr/build-ci/tests/prop_topological_order[1]_tests.cmake")
else()
  add_test(prop_topological_order_NOT_BUILT prop_topological_order_NOT_BUILT)
endif()
