if(EXISTS "/workspace/helm-project/libs/dagr/build-ci/tests/test_transform_node[1]_tests.cmake")
  include("/workspace/helm-project/libs/dagr/build-ci/tests/test_transform_node[1]_tests.cmake")
else()
  add_test(test_transform_node_NOT_BUILT test_transform_node_NOT_BUILT)
endif()
