if(EXISTS "/workspace/helm-project/libs/tick/build-ci/tests/test_noleap[1]_tests.cmake")
  include("/workspace/helm-project/libs/tick/build-ci/tests/test_noleap[1]_tests.cmake")
else()
  add_test(test_noleap_NOT_BUILT test_noleap_NOT_BUILT)
endif()
