if(EXISTS "/workspace/helm-project/libs/tick/build-ci/tests/test_alarm[1]_tests.cmake")
  include("/workspace/helm-project/libs/tick/build-ci/tests/test_alarm[1]_tests.cmake")
else()
  add_test(test_alarm_NOT_BUILT test_alarm_NOT_BUILT)
endif()
