add_test([=[NoLeapCalendar.RoundTrip]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapCalendar.RoundTrip]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapCalendar.RoundTrip]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapCalendar.RoundTripReverse]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapCalendar.RoundTripReverse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapCalendar.RoundTripReverse]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapCalendar.YearIsExactly365Days]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapCalendar.YearIsExactly365Days]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapCalendar.YearIsExactly365Days]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapEdgeCases.RejectsFeb29]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapEdgeCases.RejectsFeb29]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapEdgeCases.RejectsFeb29]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapEdgeCases.RejectsFeb29AnyYear]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapEdgeCases.RejectsFeb29AnyYear]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapEdgeCases.RejectsFeb29AnyYear]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapEdgeCases.InvalidMonthZero]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapEdgeCases.InvalidMonthZero]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapEdgeCases.InvalidMonthZero]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapEdgeCases.InvalidMonthThirteen]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapEdgeCases.InvalidMonthThirteen]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapEdgeCases.InvalidMonthThirteen]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapEdgeCases.InvalidHour]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapEdgeCases.InvalidHour]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapEdgeCases.InvalidHour]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapEdgeCases.Year365Days]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapEdgeCases.Year365Days]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapEdgeCases.Year365Days]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapEdgeCases.FebAlways28Days]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapEdgeCases.FebAlways28Days]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapEdgeCases.FebAlways28Days]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapUnit.RejectsFeb29]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapUnit.RejectsFeb29]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapUnit.RejectsFeb29]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[NoLeapUnit.InvalidMonth]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_noleap [==[--gtest_filter=NoLeapUnit.InvalidMonth]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[NoLeapUnit.InvalidMonth]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_noleap_TESTS NoLeapCalendar.RoundTrip NoLeapCalendar.RoundTripReverse NoLeapCalendar.YearIsExactly365Days NoLeapEdgeCases.RejectsFeb29 NoLeapEdgeCases.RejectsFeb29AnyYear NoLeapEdgeCases.InvalidMonthZero NoLeapEdgeCases.InvalidMonthThirteen NoLeapEdgeCases.InvalidHour NoLeapEdgeCases.Year365Days NoLeapEdgeCases.FebAlways28Days NoLeapUnit.RejectsFeb29 NoLeapUnit.InvalidMonth)
