if(EXISTS "/workspace/helm-project/libs/tick/build-ci/tests/test_sync[1]_tests.cmake")
  include("/workspace/helm-project/libs/tick/build-ci/tests/test_sync[1]_tests.cmake")
else()
  add_test(test_sync_NOT_BUILT test_sync_NOT_BUILT)
endif()
