add_test([=[Synchronization.HeartbeatDividesAllSteps]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=Synchronization.HeartbeatDividesAllSteps]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Synchronization.HeartbeatDividesAllSteps]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Synchronization.AllStepsDivideSyncPeriod]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=Synchronization.AllStepsDivideSyncPeriod]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Synchronization.AllStepsDivideSyncPeriod]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[Synchronization.PhaseAlignmentMatchesModulo]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=Synchronization.PhaseAlignmentMatchesModulo]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[Synchronization.PhaseAlignmentMatchesModulo]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SyncUnit.ESMTimesteps]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=SyncUnit.ESMTimesteps]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SyncUnit.ESMTimesteps]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SyncUnit.SingleElement]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=SyncUnit.SingleElement]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SyncUnit.SingleElement]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SyncUnit.EmptyCollectionThrows]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=SyncUnit.EmptyCollectionThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SyncUnit.EmptyCollectionThrows]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SyncUnit.ZeroStepThrows]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=SyncUnit.ZeroStepThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SyncUnit.ZeroStepThrows]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SyncUnit.NegativeStepThrows]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=SyncUnit.NegativeStepThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SyncUnit.NegativeStepThrows]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SyncUnit.LCMOverflowThrows]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=SyncUnit.LCMOverflowThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SyncUnit.LCMOverflowThrows]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SyncUnit.PhaseAlignedAtBase]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=SyncUnit.PhaseAlignedAtBase]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SyncUnit.PhaseAlignedAtBase]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SyncUnit.PhaseAlignedBeforeBaseReturnsFalse]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=SyncUnit.PhaseAlignedBeforeBaseReturnsFalse]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SyncUnit.PhaseAlignedBeforeBaseReturnsFalse]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
add_test([=[SyncUnit.PhaseAlignedZeroStepThrows]=]  /workspace/helm-project/libs/tick/build-ci/tests/test_sync [==[--gtest_filter=SyncUnit.PhaseAlignedZeroStepThrows]==] --gtest_also_run_disabled_tests)
set_tests_properties([=[SyncUnit.PhaseAlignedZeroStepThrows]=]  PROPERTIES WORKING_DIRECTORY /workspace/helm-project/libs/tick/build-ci/tests SKIP_REGULAR_EXPRESSION [==[\[  SKIPPED \]]==])
set(  test_sync_TESTS Synchronization.HeartbeatDividesAllSteps Synchronization.AllStepsDivideSyncPeriod Synchronization.PhaseAlignmentMatchesModulo SyncUnit.ESMTimesteps SyncUnit.SingleElement SyncUnit.EmptyCollectionThrows SyncUnit.ZeroStepThrows SyncUnit.NegativeStepThrows SyncUnit.LCMOverflowThrows SyncUnit.PhaseAlignedAtBase SyncUnit.PhaseAlignedBeforeBaseReturnsFalse SyncUnit.PhaseAlignedZeroStepThrows)
