if(EXISTS "/workspace/helm-project/libs/span/build-ci/tests/span_unit_tests[1]_tests.cmake")
  include("/workspace/helm-project/libs/span/build-ci/tests/span_unit_tests[1]_tests.cmake")
else()
  add_test(span_unit_tests_NOT_BUILT span_unit_tests_NOT_BUILT)
endif()
