target-version = "py310"
line-length = 132

[lint]
select = [
    "E",  # pycodestyle errors
    "W",  # pycodestyle warnings
    "F",  # pyflakes
    "I",  # isort
    "B",  # flake8-bugbear
    "C4",  # flake8-comprehensions
    "UP",  # pyupgrade
]
ignore = [
    "E501",  # line too long
    "B028",  # explicit `stacklevel` in `warnings.warn`
]

[lint.per-file-ignores]
"libs/halo/spack/package.py" = ["F405"]
