// ─── Property-Based Tests: conf::Config round-trip type fidelity ─────────────
// Feature: conf-config-parser, Property 1: Round-Trip
//
// Uses RapidCheck to verify that a typed value serialized into a minimal YAML
// document, parsed by a conf::Config, and read back with the matching typed
// accessor equals the original value:
//
//   * 32-bit integers          : exactly equal           (get_int)
//   * finite doubles           : bit-for-bit equal        (get_double)
//   * booleans                 : exactly equal            (get_bool)
//   * strings (0..65535 bytes) : byte-for-byte identical   (get_string)
//   * a map of mixed typed keys: each key equals its original (mixed accessors)
//
// Each property drives a value through the PUBLIC API only
// (Config::from_string + the get_* accessors); the yaml-cpp backend stays an
// invisible implementation detail. The tests run single-process with no MPI and
// >= 100 generated iterations (RC_PARAMS=max_success=100, set by the harness).
//
// Serialization notes (a TEST concern, not an implementation concern):
//   * Doubles are emitted with std::numeric_limits<double>::max_digits10 (17)
//     significant digits, which uniquely identifies every finite double, so the
//     parse round-trips bit-exactly. NaN/Inf are excluded (YAML .nan/.inf
//     scalar semantics differ from the IEEE bit patterns) by restricting the
//     generator to finite values.
//   * Strings are emitted as a single-line YAML double-quoted scalar with
//     explicit escaping. Inside a double-quoted scalar only '\\' and '"' are
//     special; every other printable ASCII byte is emitted literally (preserving
//     all internal/leading/trailing whitespace) and every control byte is
//     emitted as a \xNN escape. Generated bytes are restricted to the 7-bit
//     ASCII range 0x00..0x7F: a YAML \xNN escape denotes the Unicode code point
//     U+00NN, so bytes >= 0x80 would be re-encoded as MULTI-byte UTF-8 and would
//     NOT round-trip byte-identically — a serialization limitation of the YAML
//     text format, not of CONF. The 0x00..0x7F range still exercises NUL, every
//     whitespace and control character, digits, letters, and punctuation across
//     lengths from 0 up to tens of thousands of bytes, keeping coverage as broad
//     as reliably possible while guaranteeing byte-identical fidelity.
//
// **Validates: Requirements 27.1, 27.2, 27.3, 27.4, 27.5**
// ─────────────────────────────────────────────────────────────────────────────

#include <gtest/gtest.h>
#include <rapidcheck.h>
#include <rapidcheck/gtest.h>

#include <cmath>
#include <cstdint>
#include <cstring>
#include <iomanip>
#include <limits>
#include <sstream>
#include <string>

#include <conf/config.hpp>

namespace {

// ─── Serialization helpers (build minimal YAML text faithfully) ──────────────

/// Format a finite double with 17 significant decimal digits. max_digits10 (17)
/// is the smallest precision that round-trips every finite double exactly, so
/// the resulting text re-parses to the identical bit pattern.
std::string format_double(double value) {
    std::ostringstream oss;
    oss << std::setprecision(std::numeric_limits<double>::max_digits10) << value;
    return oss.str();
}

/// Encode a byte string as a single-line YAML double-quoted scalar (including
/// the surrounding quotes). '\\' and '"' are escaped; printable ASCII bytes are
/// emitted literally; control bytes become \xNN escapes. Input bytes are assumed
/// to be in 0x00..0x7F so every \xNN escape denotes a single-byte code point.
std::string yaml_double_quoted(const std::string& bytes) {
    static constexpr char kHex[] = "0123456789ABCDEF";
    std::string out;
    out.reserve(bytes.size() + 2);
    out.push_back('"');
    for (const unsigned char c : bytes) {
        if (c == '\\') {
            out += "\\\\";
        } else if (c == '"') {
            out += "\\\"";
        } else if (c >= 0x20 && c <= 0x7E) {
            out.push_back(static_cast<char>(c));
        } else {
            // Control byte (0x00..0x1F or 0x7F): \xNN. NN < 0x80, so yaml-cpp
            // decodes the code point to exactly one byte.
            out += "\\x";
            out.push_back(kHex[(c >> 4) & 0xF]);
            out.push_back(kHex[c & 0xF]);
        }
    }
    out.push_back('"');
    return out;
}

// ─── Generators ──────────────────────────────────────────────────────────────

/// Any finite double, drawn uniformly across the IEEE-754 bit space (covering
/// subnormals, huge, and tiny magnitudes) with NaN/Inf rejected.
rc::Gen<double> finite_double() {
    return rc::gen::suchThat(
        rc::gen::map(rc::gen::arbitrary<std::uint64_t>(),
                     [](std::uint64_t bits) {
                         double d = 0.0;
                         std::memcpy(&d, &bits, sizeof(d));
                         return d;
                     }),
        [](double d) { return std::isfinite(d); });
}

/// A byte string over the 7-bit ASCII range 0x00..0x7F; guarantees
/// byte-identical YAML double-quoted round-trips. The length scales with
/// RapidCheck's size parameter, which ramps from 0 toward kNominalSize (100)
/// across the run; the scale factor (655) lets the length reach the documented
/// 0..65,535-byte range (Requirement 27.4) at maximum size while still
/// generating short strings early — preserving content diversity and shrinking.
rc::Gen<std::string> ascii_bytes() {
    return rc::gen::scale(
        655.0,
        rc::gen::container<std::string>(rc::gen::map(
            rc::gen::inRange<int>(0x00, 0x80),
            [](int b) { return static_cast<char>(b); })));
}

}  // namespace

// ─── Property 1a: 32-bit integer round-trip is exact ─────────────────────────
// Feature: conf-config-parser, Property 1: Round-Trip
//
// **Validates: Requirements 27.1**

RC_GTEST_PROP(RoundTripProperty1, IntExact, ()) {
    const std::int32_t value = *rc::gen::arbitrary<std::int32_t>();

    const conf::Config cfg =
        conf::Config::from_string("k: " + std::to_string(value));

    RC_ASSERT(cfg.get_int("k") == static_cast<int>(value));
}

// ─── Property 1b: finite double round-trip is bit-for-bit exact ──────────────
// Feature: conf-config-parser, Property 1: Round-Trip
//
// **Validates: Requirements 27.2**

RC_GTEST_PROP(RoundTripProperty1, DoubleBitExact, ()) {
    const double value = *finite_double();

    const conf::Config cfg =
        conf::Config::from_string("k: " + format_double(value));

    // Zero tolerance: the 17-significant-digit representation must reparse to the
    // identical value. (== treats -0.0 and +0.0 as equal, matching the accessor
    // contract; the chosen precision preserves the sign bit regardless.)
    RC_ASSERT(cfg.get_double("k") == value);
}

// ─── Property 1c: boolean round-trip is exact ────────────────────────────────
// Feature: conf-config-parser, Property 1: Round-Trip
//
// **Validates: Requirements 27.3**

RC_GTEST_PROP(RoundTripProperty1, BoolExact, ()) {
    const bool value = *rc::gen::arbitrary<bool>();

    const conf::Config cfg =
        conf::Config::from_string(std::string("k: ") + (value ? "true" : "false"));

    RC_ASSERT(cfg.get_bool("k") == value);
}

// ─── Property 1d: string round-trip is byte-for-byte identical ───────────────
// Feature: conf-config-parser, Property 1: Round-Trip
//
// Preserves all internal/leading/trailing whitespace and every control byte.
//
// **Validates: Requirements 27.4**

RC_GTEST_PROP(RoundTripProperty1, StringByteIdentical, ()) {
    const std::string value = *ascii_bytes();

    const conf::Config cfg =
        conf::Config::from_string("k: " + yaml_double_quoted(value));

    const std::string read_back = cfg.get_string("k");

    // Compare through a bool so RC_ASSERT never has to render raw control bytes;
    // RapidCheck still reports the generated `value` on a counterexample.
    const bool byte_identical =
        read_back.size() == value.size() && read_back == value;
    RC_ASSERT(byte_identical);
}

// ─── Property 1e: a map of mixed typed keys round-trips per accessor ─────────
// Feature: conf-config-parser, Property 1: Round-Trip
//
// A single document carrying one int, one double, one bool, and one string key,
// each read back with its matching accessor, equals the corresponding original.
//
// **Validates: Requirements 27.5**

RC_GTEST_PROP(RoundTripProperty1, MixedTypedMap, ()) {
    const std::int32_t i_value = *rc::gen::arbitrary<std::int32_t>();
    const double d_value = *finite_double();
    const bool b_value = *rc::gen::arbitrary<bool>();
    const std::string s_value = *ascii_bytes();

    std::string doc;
    doc += "i: " + std::to_string(i_value) + "\n";
    doc += "d: " + format_double(d_value) + "\n";
    doc += std::string("b: ") + (b_value ? "true" : "false") + "\n";
    doc += "s: " + yaml_double_quoted(s_value) + "\n";

    const conf::Config cfg = conf::Config::from_string(doc);

    RC_ASSERT(cfg.get_int("i") == static_cast<int>(i_value));
    RC_ASSERT(cfg.get_double("d") == d_value);
    RC_ASSERT(cfg.get_bool("b") == b_value);

    const std::string s_read = cfg.get_string("s");
    const bool s_identical =
        s_read.size() == s_value.size() && s_read == s_value;
    RC_ASSERT(s_identical);
}
