if(EXISTS "/workspace/helm-project/libs/blend/build-ci/tests/test_step_blend[1]_tests.cmake")
  include("/workspace/helm-project/libs/blend/build-ci/tests/test_step_blend[1]_tests.cmake")
else()
  add_test(test_step_blend_NOT_BUILT test_step_blend_NOT_BUILT)
endif()
