[build-system]
requires = ["scikit-build-core>=0.5", "nanobind>=1.6.0", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "axis-regrid"
version = "0.1.0"
description = "Arbitrary eXgrid Interpolation Solver (AXIS) Python bindings"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
dependencies = [
    "cf-xarray",
    "dask",
    "netCDF4",
    "numpy",
    "xarray",
]

[dependency-groups]
test = [
    "pyproj",
    "pytest",
    "scipy",
]

[project.scripts]
axis-regrid = "axis.cli:main"

[tool.scikit-build]
cmake.args = [
    "-DAXIS_BUILD_PYTHON=ON",
    "-DAXIS_BUILD_TESTING=OFF",
    "-DAXIS_BUILD_FORTRAN=OFF",
    "-DAXIS_BUILD_BENCHMARKS=OFF",
    "-DAXIS_BUILD_EXAMPLES=OFF"
]
cmake.source-dir = "."
