[build-system]
requires = ["scikit-build-core>=0.5", "nanobind>=2.0.0", "numpy"]
build-backend = "scikit_build_core.build"

[project]
name = "axis-regrid"
version = "0.1.0"
description = "Arbitrary eXgrid Interpolation Solver (AXIS) Python bindings"
readme = "README.md"
requires-python = ">=3.10"
license = {text = "Apache-2.0"}
dependencies = [
    "cf-xarray",
    "numpy",
    "xarray",
]

[dependency-groups]
test = [
    "dask",
    "netCDF4",
    "pyproj",
    "pytest",
    "scipy",
]
mypy = [
    "mypy",
    #
    "pandas-stubs",
    "scipy-stubs",
    "types-pexpect",
    "types-psutil",
    "types-Pygments",
    "types-PyYAML",
]

[project.scripts]
axis-regrid = "axis.cli:main"

[tool.scikit-build]
cmake.args = [
    "-DAXIS_BUILD_PYTHON=ON",
    "-DAXIS_BUILD_TESTING=OFF",
    "-DAXIS_BUILD_FORTRAN=OFF",
    "-DAXIS_BUILD_BENCHMARKS=OFF",
    "-DAXIS_BUILD_EXAMPLES=OFF",
]
cmake.source-dir = "."

[tool.mypy]
# Get the .pyi from the installed package.
# But consider linking it to the source dir for development
# for faster dev cycles when working on typing:
#
#   ln -sf "$(uv run python -c 'import importlib.util, os; print(os.path.join(os.path.dirname(importlib.util.find_spec("axis").origin), "axis_py.pyi"))')" python/axis/
#
packages = ["axis"]
exclude = "^build.*/"
